version: '3.8'

services:
  opensips:
    image: opensips/opensips:3.4
    container_name: opensips-test
    environment:
      - OPENSIPS_SCRIPT=/etc/opensips/opensips.cfg
    volumes:
      - ./opensips/opensips.cfg:/etc/opensips/opensips.cfg:ro
      - ./opensips/users.txt:/etc/opensips/users.txt:ro
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "8888:8888/udp"  # MI Datagram port
    networks:
      - sip-test

  # call-api:
  #   image: opensips/call-api:latest
  #   container_name: call-api-test
  #   depends_on:
  #     - opensips
  #   environment:
  #     - CALL_API_WS_HOST=0.0.0.0
  #     - CALL_API_WS_PORT=5059
  #     - OPENSIPS_MI=datagram:opensips:8888
  #     - OPENSIPS_EVENT=datagram:0.0.0.0:5555
  #   ports:
  #     - "5059:5059"  # WebSocket port
  #   networks:
  #     - sip-test

  # SIPp UAS for testing
  sipp-uas:
    image: ctaloi/sipp
    container_name: sipp-uas
    depends_on:
      - opensips
    networks:
      - sip-test
    command: -sn uas -p 5061
    
  # SIPp UAC for testing
  sipp-uac:
    image: ctaloi/sipp  
    container_name: sipp-uac
    depends_on:
      - opensips
    networks:
      - sip-test
    command: -sn uac -r 1 -l 1 -m 1 opensips:5060
    profiles:
      - test

networks:
  sip-test:
    driver: bridge